### ISSUE TITLE
Consider using ">=0.8.0" for eyeglass "needs"

### ISSUE THREAD

**Issue by Digznav** [jackw/eyeglass-image-dimensions#4]
Hi,

I'm getting this messages when I compile my SASS files:

```
The following modules are incompatible with eyeglass 1.2.1:
  image-dimensions needed eyeglass ^0.8.0
```

Is it possible to change the compatibility line to "needs": ">=0.8.0" ?

As mentioned in [sass-breakpoint issue #174](https://github.com/at-import/breakpoint/issues/174):

> It maintains current compatibility and future proofs against 1.x releases of eyeglass.

**Comment by jackw** [comment]
Hi there,
Thanks for raising this and apologies for taking a while to get this up to date. Latest release should squash that incompatibility message for you.

**Comment by Digznav** [comment]
Thanks a lot :D 👍
